spring:
  application:
    name: learnsboot

  datasource:
    url: jdbc:postgresql://localhost:5432/invmgmt
    username: postgresinv
    password: allgoodthings
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        globally_quoted_identifiers: true
    open-in-view: false