server:
  port: 8765
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev

---

spring:
  application:
    name: learnsboot
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/invmgmt
    username: postgresinv
    password: allgoodthings
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        '[globally_quoted_identifiers]': true
    open-in-view: false

---

spring:
  application:
    name: learnsboot
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/invmgmtTest
    username: postgresinv
    password: allgoodthings
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        '[globally_quoted_identifiers]': true
    open-in-view: false